name: Java CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    
    - name: build and test cadc-registry
      run: cd cadc-registry && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-vosi
      run: cd cadc-vosi && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-test-vosi
      run: cd cadc-test-vosi && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build reg
      run: cd reg && ../gradlew --info clean build compileIntTest javadoc checkstyleMain

